function [] = stereoCalibrate()

imageFileNames1 = {'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_1.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_10.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_11.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_12.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_14.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_15.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_16.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_17.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_18.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_19.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_2.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_3.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_4.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_5.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_6.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_7.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_8.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Left\left_9.jpg',...
    };
imageFileNames2 = {'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_1.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_10.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_11.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_12.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_14.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_15.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_16.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_17.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_18.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_19.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_2.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_3.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_4.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_5.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_6.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_7.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_8.jpg',...
    'C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\Calibration Code\Stereovision\Trial #7\Right\right_9.jpg',...
    };

% Detect checkerboards in images (define corners)
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 25;  % in units of 'millimeters' -- checkerboard provided by MedView allows for consistency in size
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair -- used to define size of images
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% % Export the mat file into OTS tracking system folder
% mkdir('C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\OTSAlgorithmFolder','CalibrationIntrinsics');
% filename =('C:\Users\ginet\OneDrive\Documents\MATLAB\Capstone\OTSAlgorithmFolder\CalibrationIntrinsics\stereoParams.mat');
% save(filename,'stereoParams'); 
end

